name: Update Markdown Dates

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Get last modified dates and update Markdown files
        run: |
          FILES=("content/en/checklist.md" "content/no/sjekklisten.md")
          for FILE in "${FILES[@]}"; do
            if git diff --quiet HEAD^ -- "$FILE"; then
              echo "$FILE is unchanged, skipping."
            else
              echo "Updating $FILE"
              LAST_MODIFIED=$(date +'%Y.%m.%d')
              sed -i -E "/^(Last modified: |Sist oppdatert: ).*/s//\1$LAST_MODIFIED/" "$FILE"
              git add "$FILE"
              
              echo "$FILE updated; date set to $LAST_MODIFIED"
            fi
          done

      - name: Commit and push changes if needed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            echo "Committing and pushing"
            git commit -am "Updated dates in checklists"
            git push
          fi
