name: Update Markdown Dates

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Get last modified dates and update Markdown files
        run: |
          FILES=("path/to/file1.md" "path/to/file2.md")
          for FILE in "${FILES[@]}"; do
            if git diff --quiet HEAD^ -- "$FILE"; then
              echo "$FILE is unchanged, skipping."
            else
              LAST_MODIFIED=$(git log -1 --format="%ad" --date=format:"%Y-%m-%d" -- "$FILE")
              sed -i -E "/^(Last modified: |Sist oppdatert: ).*/s//\1$LAST_MODIFIED/" "$FILE"
            fi
          done

      - name: Commit and push changes if needed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git commit -am "Update last modified dates in Markdown files"
            git push
          fi
